name: Cloud Run Traffic Split PoC

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: 'read'
  id-token: 'write'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
  REGION: us-central1
  REPO_NAME: lab-run-traffic-management
  SERVICE_NAME: run-traffic-lab

jobs:
  # ---------------------------------------------------------
  # JOB 1: PREVIEW (Roda quando abrir ou atualizar um PR)
  # ---------------------------------------------------------
  deploy_preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

        #Aplicado o Buildx para uso de cache no Docker build.
      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image variables
        run: |
          IMAGE_TAG="pr-${{ github.event.pull_request.number }}"
          IMAGE_URL="${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/app:${IMAGE_TAG}"
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
          echo "TAG_NAME=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and Push Preview Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Preview to Cloud Run (No Traffic)
        run: |
          #Verifica se o serviço já existe
          if gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.GCP_PROJECT_ID }} > /dev/null 2>&1; then

          #Caso o serviço já exista, vai fazer o deploy de uma nova revisão em modo preview (sem trafego).
            echo "Serviço '${{ env.SERVICE_NAME }}' já existe. Realizando deploy de PREVIEW (--no-traffic)..."
            gcloud run deploy ${{ env.SERVICE_NAME }} \
              --image ${{ env.IMAGE_URL }} \
              --region ${{ env.REGION }} \
              --project ${{ env.GCP_PROJECT_ID }} \
              --allow-unauthenticated \
              --no-traffic \
              --tag ${{ env.TAG_NAME }} \
              --set-env-vars APP_VERSION=${{ env.TAG_NAME }} \
              --quiet
          
          #Caso o serviço não exista, vai fazer criar o serviço com a primeira revisão e direcionar 100% do trafego.
          else
            echo "Serviço '${{ env.SERVICE_NAME }}' não encontrado. Realizando deploy INICIAL (100% tráfego)..."
            gcloud run deploy ${{ env.SERVICE_NAME }} \
              --image ${{ env.IMAGE_URL }} \
              --region ${{ env.REGION }} \
              --project ${{ env.GCP_PROJECT_ID }} \
              --allow-unauthenticated \
              --tag ${{ env.TAG_NAME }} \
              --set-env-vars APP_VERSION=${{ env.TAG_NAME }} \
              --quiet
          fi

  # ---------------------------------------------------------
  # JOB 2: PRODUÇÃO (Roda quando criar uma Tag vX.Y.Z)
  # ---------------------------------------------------------
  deploy_prod:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      #Aplicado o Buildx para uso de cache no Docker build.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Image Variables
        run: |
          VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//')
          IMAGE_URL="${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/app:${VERSION}"
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Prod Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Production to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_URL }} \
            --region ${{ env.REGION }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --allow-unauthenticated \
            --set-env-vars APP_VERSION=${{ env.VERSION }} \
            --quiet
        
        #Aplica o direcionamento de 100% do trafego para ultima versao.
      - name: Routing traffic to latest revision (100%)
        run: |
          gcloud run services update-traffic ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --to-latest \
            --quiet